.Dd August 23 2019
.Dt ROGUE 6
.nh
.Os
.Sh NAME
.Nm rogue
.Nd exploring the Dungeons of Doom
.Sh SYNOPSIS
.Bk -words
.Nm
.Op Fl d Ar seed
.Op Fl n Ar name
.Nm
.Fl s
.Ek
.Sh DESCRIPTION
.Nm
is a computer fantasy game. The object of the game is to survive the
attacks of various monsters and get a lot of gold. To win the game you
must locate the Amulet of Yendor which is somewhere below the 20th level
of the dungeon and get it out.
.Pp
Options:
.Bl -tag -width Ds
.It Fl d Ar seed
sets the random number seed to the given value. 32-bit integer. If not
supplied, a random seed will be used for a new game.
.It Fl n Ar name
sets the player's name. Restricted to 18 bytes to fit on your
tombstone. Use the same name to restore from a saved game.
.It Fl s
shows the high score list and then quits the game.
.El
.Pp
There may be other options depending on how
.Nm
was compiled.
.Ss \&An Overview of the Dungeon
What do all these things on the screen mean?
.Bd -literal -offset indent
  ---------------------
  |...................+
  |...@...........[...|
  |........B..........|
  |...................|
  --------+------------

Level: 1  Gold: 0      Hp: 12(12)  Str: 16  Ac: 6  Exp: 1/0
.Ed
.Pp
At the bottom of the screen are a few pieces of cryptic information that
describe your current status.
.Qq \&Hp
or hit points are pretty important. A lower armor class is better
(this was traditional in Dungeons \&& Dragons) and can be improved by
wearing heavier armors or via enchantments. As you kill things
your
.Qq \&Exp
or experience points will go up.
.Pp
You are represented by the
.Qq @
symbol, presently within a lit room with a bat or
.Qq B
nearby (see
.Sx Monsters )
and also an item
.Qq \&[ .
.Sx Items
are picked up by moving over them.
.Pp
.Xr vi 1
motion keys plus additional keys for diagonal moves (if allowed)
move your character around the screen, among other such
.Sx Commands .
.Pp
.Qq +
are doors that lead to corridors that connect rooms;
.Qq \&.
is used for the lit floor of rooms and
.Qq #
for the floor in corridors. Stairs, unlike in various modern roguelikes,
are represented by
.Qq %
and are one-way, unless you happen to be carrying the amulet. Note that
doors cannot be entered on the diagonal, nor can monsters attack you on
the diagonal if you stand on a door.
.Pp
Messages will be printed at the top of the screen, sometimes with a
.Qq --More--
prompt that will need to be cleared by pressing the space bar.
Messages can be made less verbose with the
.Cm terse
option, see
.Sx Options .
.Bd -literal -offset indent
        ##                                              ---
  -------+------            -------------            ###+
  |............|            |...........|            #  |
  |............|            |...........|            #  |%
  |............|            |...........|            #  |
  |............|            |...........+#############  |
  ------+-------            -------+-----               -+-
        #                          #                     #
        ####                       ###                   ##
    -------+-----------           ---+---                -@-
    |                  |          |)....|                ...
    |                  +####      |.....|
    |                  |   #######+.]...|
    |                  |          -------
     -------------------
Level: 9  Gold: 1127   Hp: 47(47)  Str: 14  Ac: 6   Exp: 6/226
.Ed
.Ss Commands
Some commands take time (such as removing armor) while others do not.
Two commands can be used to learn about other commands and features of
the dungeon.
.Bl -tag -width Ds
.It Cm \&?
Displays a list of available commands.
.It Cm /
Identifies the things you see on the screen.
.El
.Pp
Direction commands move you about the dungeon. With the shift key they
will run in the given direction. They can also be used as modifiers for
other commands, such as
.Cm t
for throw.
.Bl -tag -width Ds
.It Cm h
Move left.
.It Cm j
Move down.
.It Cm k
Move up.
.It Cm l
Move right.
.It Cm y
Move up and left.
.It Cm u
Move up and right.
.It Cm b
Move down and left.
.It Cm n
Move down and right.
.El
.Pp
The remainder of the commands carry out various actions.
.Bl -tag -width Ds
.It Cm t Ar dir
Throw something in the given motion direction.
.It Cm f Ar dir
Move until something is found in the given direction. This is more
conservative than running with shift +
.Ar dir
and is more like the
.Cm t
command of
.Xr vi 1
in that it stops next to the found object, not on said object.
.It Cm p Ar dir
Zap a wand in a direction.
.It Cm z
Zap a wand.
.It Cm >
Go down a staircase. Staircase are represented by
.Qq % .
.It Cm <
With the amulet in hand, use this command to climb up at a staircase.
.It Cm s
Search adjacent for traps or secret doors. It may take multiple attempts
to find these. Multiple attempts without moving increases the odds that
a secret door will be found.
.It Cm \&.
Rest. A numeric prefix will rest for longer though will allow wandering
monsters a free hit should they find you.
.It Cm Space
Used to be the traditional command to rest, though is now only
used to clear
.Qq "--More--"
prompts, as accidentally resting next to a monster is often unideal.
.It Cm i
Display the inventory.
.It Cm I Ar slot
Display the given inventory item.
.It Cm q
Quaff a potion.
.It Cm r
Read a paper.
.It Cm e Cm E
Eat food. (Uppercase 
.Cm E
is due to an
.Nm Angband
habit.)
.It Cm w
Wield a weapon. To fire an arrow first wield the bow.
.It Cm W
Wear armor. Only one piece can be worn at a time.
.It Cm T
Take armor off.
.It Cm P
Put on a ring.
.It Cm R
Remove a ring.
.It Cm d
Drop an object.
.It Cm c
Call an object (rename it to something else). See also the
.Cm askme
option. The length of a name is limited to 32 characters.
The
.Dv -
key at the beginning will preserve the existing name.
.It Cm o
Examine or set
.Sx Options .
.It Cm C-l
Redraw the screen.
.It Cm C-r
Repeat the last message.
.It Cm esc
Cancel a command.
.It Cm v
Program version number.
.It Cm S
Save game and exit from
.Nm . Confirm with
.Cm Y .
A saved game should be restored if the same
.Fl n
flag is given to
.Nm .
.It Cm Q
Quit the current game. Confirm with
.Cm Y .
.El
.Pp
As in
.Xr vi 1
you may prefix some of the commands with a number to indicate how many
times that action should be repeated. For example
.Cm 5l
would move five spaces to the left. If resting beware that this will
let a monster get a free hit on you before interrupting. See also the
.Cm flush
option.
.Ss Items
Pick these up by moving over them.
.Bl -tag -width Ds
.It !
A flask containing a magic potion.
.It %
Not an item! This is a one-way staircase to the next level.
.It )
A weapon to wield.
.It *
A pile or pot of gold.
.It /
A stick or wand of some sort.
.It :
A piece of food.
.It =
A ring to put on.
.It ?
A piece of paper, usually a magic scroll.
.It ]
A piece of armor to wear.
.El
.Ss Monsters
There are twenty-six different monsters. Some are hostile, and some
start to wander about the level.
.Bl -tag -width Ds
.It A
Giant ant.
.It B
A bat, or possibly someone dressed up as a bat.
.It C
Centaur.
.It D
Dragon.
.It E
Floating eye.
.It F
Violet fungi.
.It G
Gnome.
.It H
Hobgoblin.
.It J
Jackal.
.It K
Kobold.
.It L
Leprechaun.
.It M
Mimic.
.It N
Nymph.
.It O
Orc.
.It P
Purple worm.
.It Q
Quasit.
.It R
Rust monster.
.It S
Snake.
.It T
Troll.
.It U
Umber hulk.
.It V
Vampire.
.It W
Wraith.
.It X
Xorn.
.It Y
Yeti.
.It Z
Zombie.
.El
.Ss Options
These can be set via the
.Ev ROGUEOPTS
environment variable or in-game with the
.Cm o
command.
.Pp
The
.Cm o
command places the cursor by the value of the first option and waits for
you to type. You can type a RETURN which means to go to the next option,
a
.Cm \&-
which means to go to the previous option, an ESCAPE which means to
return to the game, or you can give the option a value. For boolean
options this merely involves pressing
.Cm t
for true or
.Cm f
for false. For string options, type the new value followed by a RETURN.
.Bl -tag -width Ds
.It Cm askme , Cm noaskme
After reading a scroll or quaffing a potion that does not self identify
upon use,
.Nm
will ask you what to name it so you can recognize it in the future. On
by default.
.It Cm flush , Cm noflush
If flush is set, all typeahead is thrown away after each round of
battle. This is useful for those who type way ahead and watch to their
dismay as a Kobold kills them. Off by default.
.It Cm jump , Cm nojump
If this option is set, running moves will not be displayed until you
reach the end of the move. This saves considerable CPU time and display
time. This option defaults to on if you are using a slow terminal,
otherwise it is off by default.
.It Cm step , Cm nostep
When this is set, lists of things are displayed one item at a time on
the top of the screen, rather than clearing the screen, displaying the
list, then re-displaying the dungeon level.
.It Cm terse , Cm noterse
Useful for those who are tired of the sometimes lengthy messages. This
is a useful option for those on slow terminals. This option defaults to
on if you are using a slow terminal, otherwise it is off by default.
.El
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev ROGUEHOME
Directory that will be used for the score and save files. The current
working directory is used if this is not set.
.It Ev ROGUEOPTS
A comma separated list of values for the various
.Sx Options .
These are only read for new games.
.El
.Sh EXIT STATUS
.Nm
exits with a 0 on victory, and >0 in every other case.
.Sh SEE ALSO
.Nm Angband ,
.Nm Brogue ,
.Nm crawl ,
.Nm POWDER ,
.Nm Sil
.Sh HISTORY
This version began from a
.Pa rogue3.6.3-src.tar.gz
file found somewhere on the Internet and has been updated to compile on
modern unix systems, plus a bunch of other changes and cleanups,
hopefully without introducing too many new bugs.
.Sh AUTHORS
.An Ken Arnold ,
.An Michael Toy ,
.An Glenn Wichman
.Pp
Machine Dependent Code for Porting Unix/Curses games:
.Pp
.An Nicholas J. Kisseberth
.Ss Acknowledgements
Rogue was originally conceived of by Glenn Wichman and Michael Toy. The
help of Ken Arnold in making the program easier to use and putting the
finishing touches on is greatly appreciated. I would also like to thank
Marty McNary, Scott Nelson, Daniel Jensen, Kipp Hickman, Joe Kalash,
Steve Maurer, Bill Joy, Mark Horton and Jan Miller for their ideas and
assistance.
.Sh COPYRIGHT
Rogue: Exploring the Dungeons of Doom
.Pp
Copyright (C) 1980, 1981 Michael Toy, Ken Arnold, and Glenn Wichman
.Pp
All rights reserved.
.Sh CAVEATS
.Nm
is an old game that shows its age.
.Bl -bullet
.It
The interface for selecting items has been much improved on by
new roguelikes. In particular it is very easy to throw away your bow
while shooting, and the extra trips to the inventory list to pick a
letter are cumbersome, especially given that the letters move around
as your inventory changes. Cancelling an action is also difficult.
.It
The need to carry spare armor because of rust monsters compounds
inventory problems, assuming you find any spare armor, especially given
how frequently rust monsters appear, their odds of hitting, and how
long they take to kill.
.Nm Brogue
offers a protect armor scroll (or reasonable odds of punching an acid
mound to death, among other options) and
.Nm crawl
has made corrosion a temporary effect.
.It
It is difficult to heal up by resting; modern roguelikes typically
offer a rest command that will be interrupted when a monster appears.
On the other hand, a desperate plunge into a lethal dungeon could be a
design goal.
.Sh BUGS
.Qq Probably infinite.
.Pp
Soft locks involving floating eyes have been worked around by making
floating eyes more lethal. You're welcome.
.Pp
The RNG is bad and exhibits non-random results from inputs such as
repeated coinflips.
.Pp
Scrolls can be read while blind. Other roguelikes disallow this, but
maybe the scrolls use braille? Also throwing things can pass along
confuse and somehow identify monsters.
.Ss Known Issues
If
.Nm
goes to 100% CPU try sending the process a
.Dv HUP
signal then restoring from the save game file. Wizard mode or more
likely a debug build will be necessary to trace down the issue.
.Sh SECURITY CONSIDERATIONS
An abundance of C code from the 1980s.
