#!/usr/bin/env expect
#
# roguereplay - replays a rogue game from a given key log file

package require Tcl 8.5

if {[llength $argv] != 1} {
    puts stderr "Usage: $argv0 logfile"
    exit 1
}

set file [lindex $argv 0]
set logf [open $file]

# assume the file name is something.$SEED
set env(SEED) [lindex [split $file .] 1]

set env(ROGUEHOME) [file normalize ~/share/rogue]
set env(ROGUEOPTS) name=Null,askme,noflush,jump

set rogue [open "| rogue -r" w]
fconfigure $rogue -buffering none

while {1} {
    set ch [read $logf 1]
    if {$ch eq ""} {
        catch {close $rogue}
        exit 0
    }
    if {[catch {puts -nonewline $rogue $ch} msg]} {
        puts stderr "rogue write failed: $msg"
        exit 1
    }
    sleep 0.5
}
