#!/bin/sh
#
# roguerun - a rogue wrapper that uses an existing save file or starts
# a new game. rogue(6) has details on what ROGUEOPTS may contain
# ("askme" being important, unless you are good at memorizing random
# scroll names)

# avoid the default of rogue writing directly to ~/
export ROGUEHOME="$HOME"/share/rogue
export ROGUEOPTS="name=Null,askme,noflush,jump"

# if enable keylogging then there is no savefile support
#export ROGUELOG=1

# NOTE the save file could be in ROGUEOPTS or could defult to being
# under ROGUEHOME or HOME, depending. this makes simplifying assumptions
savefile=$ROGUEHOME/rogue36.sav

[ -e "$savefile" ] || savefile=

exec rogue $savefile
